version: '2.1'
services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - "8000:9090"
      - "9191:9191"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - web
   
  db:
    image: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      ENV: ENV 
    volumes:
      - ./app:/app
    ports:
      - "9090:9090"
      - "80:80"
    depends_on:
      - db
    links:
      - db